### ISSUE TITLE
Добавить ограничение на комбинацию условий в `unless`

### ISSUE THREAD

**Issue by KELiON** [appbooster/rubocop_config#11]
```ruby
# GOOD
unless something_is_good?

# BAD
unless foo? && bar? || baz?
```

Код можно упереть тут: https://github.com/wata727/rubocop/commit/da4ed994d5fd263c4e08d4df98ea6cd716244ca3

Добавление кастомных копов в rubocop: https://github.com/bbatsov/rubocop/blob/master/manual/extensions.md

**Comment by moofkit** [comment]
👍

**Comment by foxy-eyed** [comment]
Даааа!

**Comment by moofkit** [comment]
#12 solved
