### ISSUE TITLE
Автодеплой с тревиса

### ISSUE THREAD

**Issue by KELiON** [appbooster/rubocop_config#14]
Нужно чекнуть, есть ли возможность для публичных репозиториев хранить секретные ключи (для rubygems аккаунта, в этом случае). Если можно — то было бы круто автоматически релизить версию при создании тега на гитхабе (вместо ручного апдейта версии и паблишинга в рубигемс).

**Comment by moofkit** [comment]
да так то там уже все автоматизировано.
`bundle exec rake release` создает тег и пушит в рубигемс.

но да приходится создавать отдельный коммит с `bump version`
