### ISSUE TITLE
Cop Style/FileName: добавить исключения

### ISSUE THREAD

**Issue by foxy-eyed** [appbooster/rubocop_config#2]
Предлагаю добавить следующую вещь в дефолтный кофиг:
```
Style/FileName:
  Exclude:
    - "Capfile"
    - "Vagrantfile"
```
Думаю, это актуально для большинства наших проектов.
Я так понимаю, мы пока только на калькуляторе внедрили текущий конфиг, а там пока деплой не настроен, не успели столкнуться :)
Согласны?

**Comment by moofkit** [comment]
👍

**Comment by KELiON** [comment]
> Предлагаю добавить следующую вещь в дефолтный кофиг:

Думаю можно сразу пулл-реквестом делать) 👍
