### ISSUE TITLE
Автодеплой

### ISSUE THREAD

**Issue by KELiON** [appbooster/rubocop_config#5]
Было бы круто, чтобы гем не нужно было выкладывать руками, а чтобы просто при обновлении версии CI сам заливал бы новую версию

**Comment by moofkit** [comment]
@KELiON а его не надо никуда выкладывать жеж.
просто создаешь PR с новой версией когда надо

**Comment by KELiON** [comment]
А, точно, мы же в гемфайле его из гита прописываем
