### ISSUE TITLE
Ставить rubocop-rspec автоматом или явно указать зависимости в документации

### ISSUE THREAD

**Issue by yarafan** [appbooster/rubocop_config#6]
Сконфигурировал согласно README, при проверке начал ругаться, что нет файла rubocop-rspec

**Comment by moofkit** [comment]
а можешь кинуть ошибку?
по идее должен тащить как зависимость

**Comment by KELiON** [comment]
Скорее [вот тут](https://github.com/appbooster/rubocop_config/blob/master/appbooster_rubocop_config.gemspec#L36) нужно сделать

```diff
- spec.add_development_dependency "rubocop-rspec", "~> 1.20"
+ spec.add_dependency "rubocop-rspec", "~> 1.20"
```

**Comment by moofkit** [comment]
@KELiON 👍
